#ifndef QIWO_TEST_STUB_IBUS_H_
#define QIWO_TEST_STUB_IBUS_H_

#include <glib.h>

#define IBUS_ORIENTATION_SYSTEM 0
#define IBUS_ORIENTATION_HORIZONTAL 1
#define IBUS_ORIENTATION_VERTICAL 2

#endif  // QIWO_TEST_STUB_IBUS_H_
